name: CI
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        cache: yarn
        node-version: 16
    - run: yarn install --frozen-lockfile
    - run: yarn typecheck
    - run: yarn spellcheck
    - run: yarn build