name: Documentation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build docs
      run: sh ./scripts/build-docs.sh

    - name: Publish docs
      env:
        GITHUB_API_KEY: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      run: sh ./scripts/publish-docs.sh
